/*   -*- buffer-read-only: t -*- vi: set ro:
 *  
 *  DO NOT EDIT THIS FILE   (opts.c)
 *  
 *  It has been AutoGen-ed  June 26, 2011 at 07:40:00 AM by AutoGen 5.11.10pre11
 *  From the definitions    opts.def
 *  and the template file   options
 *
 * Generated from AutoOpts 35:0:10 templates.
 *
 *  AutoOpts is a copyrighted work.  This source file is not encumbered
 *  by AutoOpts licensing, but is provided under the licensing terms chosen
 *  by the autogen author or copyright holder.  AutoOpts is
 *  licensed under the terms of the LGPL.  The redistributable library
 *  (``libopts'') is licensed under the terms of either the LGPL or, at the
 *  users discretion, the BSD license.  See the AutoOpts and/or libopts sources
 *  for details.
 *
 * This source file is copyrighted and licensed under the following terms:
 *
 *  Copyright (C) 1992-2011 Bruce Korb, all rights reserved.
 *  This is free software. It is licensed for use, modification and
 *  redistribution under the terms of the
 *  GNU General Public License, version 3 or later
 *      <http://gnu.org/licenses/gpl.html>
 *  
PFX>autogen is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *  
 *  autogen is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *  See the GNU General Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License along
 *  with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <sys/types.h>

#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#define OPTION_CODE_COMPILE 1
#include "opts.h"

#ifdef  __cplusplus
extern "C" {
#endif
extern FILE * option_usage_fp;

/* TRANSLATORS: choose the translation for option names wisely because you
                cannot ever change your mind. */
static char const zCopyright[273] =
"autogen (GNU AutoGen) 5.12\n\
Copyright (C) 1992-2011 Bruce Korb, all rights reserved.\n\
This is free software. It is licensed for use, modification and\n\
redistribution under the terms of the\n\
GNU General Public License, version 3 or later\n\
    <http://gnu.org/licenses/gpl.html>\n";
static char const zLicenseDescrip[603] =
"autogen is free software: you can redistribute it and/or modify it under\n\
the terms of the GNU General Public License as published by the Free\n\
Software Foundation, either version 3 of the License, or (at your option)\n\
any later version.\n\n\
autogen is distributed in the hope that it will be useful, but WITHOUT\n\
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or\n\
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License\n\
for more details.\n\n\
You should have received a copy of the GNU General Public License along\n\
with this program.  If not, see <http://www.gnu.org/licenses/>.\n";

extern tUsageProc optionUsage;

/*
 *  global included definitions
 */
#include "autogen.h"
#ifdef HAVE_DLOPEN
# ifdef HAVE_DLFCN_H
#  include <dlfcn.h>
# else
   extern void* dlopen(char const*,int);
# endif

# ifndef  RTLD_GLOBAL
#  define RTLD_GLOBAL 0
# endif

# ifndef  RTLD_NOW
#  ifdef  RTLD_LAZY
#   define RTLD_NOW DL_LAZY
#  else
#   define RTLD_NOW 0
#  endif
# endif
#endif

#if HAVE_CTYPE_H
# include <ctype.h>
#else
# define isspace(_c)  0
#endif

typedef void (init_proc_t)(void);
char const * pzTemplFileName  = NULL;
ag_bool      trace_is_to_pipe = AG_FALSE;

#ifndef NULL
#  define NULL 0
#endif

/*
 *  Templ_Dirs option description:
 */
/* TRANSLATORS: the option argument is a file name */
static char const zTempl_DirsText[] =
        "Template search directory list";
static char const zTempl_Dirs_NAME[]         = "TEMPL_DIRS";
static char const zTempl_Dirs_Name[]         = "templ-dirs";
#define TEMPL_DIRS_FLAGS       (OPTST_DISABLED | OPTST_STACKED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  Override_Tpl option description:
 */
static char const zOverride_TplText[] =
        "Override template file";
static char const zOverride_Tpl_NAME[]       = "OVERRIDE_TPL";
static char const zOverride_Tpl_Name[]       = "override-tpl";
#define OVERRIDE_TPL_FLAGS       (OPTST_DISABLED | OPTST_NO_INIT \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  Lib_Template option description:
 */
static char const zLib_TemplateText[] =
        "Library template file";
static char const zLib_Template_NAME[]       = "LIB_TEMPLATE";
static char const zLib_Template_Name[]       = "lib-template";
#define LIB_TEMPLATE_FLAGS       (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  Base_Name option description:
 */
static char const zBase_NameText[] =
        "Base name for output file(s)";
static char const zBase_Name_NAME[]          = "BASE_NAME";
static char const zBase_Name_Name[]          = "base-name";
#define BASE_NAME_FLAGS       (OPTST_DISABLED | OPTST_NO_INIT \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  Definitions option description:
 */
static char const zDefinitionsText[] =
        "Definitions input file";
static char const zDefinitions_NAME[]        = "DEFINITIONS";
static char const zNotDefinitions_Name[]     = "no-definitions";
static char const zNotDefinitions_Pfx[]      = "no";
#define zDefinitions_Name            (zNotDefinitions_Name + 3)
#define DEFINITIONS_FLAGS       (OPTST_INITENABLED | OPTST_NO_INIT \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  Load_Scheme option description:
 */
static char const zLoad_SchemeText[] =
        "Scheme code file to load";
static char const zLoad_Scheme_NAME[]        = "LOAD_SCHEME";
static char const zLoad_Scheme_Name[]        = "load-scheme";
#define LOAD_SCHEME_FLAGS       (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  Load_Functions option description:
 */
#ifdef HAVE_DLOPEN
static char const zLoad_FunctionsText[] =
        "Load scheme function library";
static char const zLoad_Functions_NAME[]     = "LOAD_FUNCTIONS";
static char const zLoad_Functions_Name[]     = "load-functions";
#define LOAD_FUNCTIONS_FLAGS       (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

#else   /* disable Load_Functions */
#define LOAD_FUNCTIONS_FLAGS       (OPTST_OMITTED | OPTST_NO_INIT)
#define zLoad_Functions_NAME      NULL
#define zLoad_FunctionsText       NULL
#define zLoad_Functions_Name      NULL
#endif  /* HAVE_DLOPEN */

/*
 *  Skip_Suffix option description with
 *  "Must also have options" and "Incompatible options":
 */
static char const zSkip_SuffixText[] =
        "Omit the file with this suffix";
static char const zSkip_Suffix_NAME[]        = "SKIP_SUFFIX";
static char const zSkip_Suffix_Name[]        = "skip-suffix";
static const int
    aSkip_SuffixCantList[] = {
    INDEX_OPT_SELECT_SUFFIX, NO_EQUIVALENT };
#define SKIP_SUFFIX_FLAGS       (OPTST_DISABLED | OPTST_STACKED | OPTST_NO_INIT \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  Select_Suffix option description:
 */
static char const zSelect_SuffixText[] =
        "specify this output suffix";
static char const zSelect_Suffix_NAME[]      = "SELECT_SUFFIX";
static char const zSelect_Suffix_Name[]      = "select-suffix";
#define SELECT_SUFFIX_FLAGS       (OPTST_DISABLED | OPTST_NO_INIT \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING) | OPTST_ARG_OPTIONAL)

/*
 *  Source_Time option description:
 */
static char const zSource_TimeText[] =
        "set mod times to latest source";
static char const zSource_Time_NAME[]        = "SOURCE_TIME";
static char const zNotSource_Time_Name[]     = "no-source-time";
static char const zNotSource_Time_Pfx[]      = "no";
#define zSource_Time_Name            (zNotSource_Time_Name + 3)
#define SOURCE_TIME_FLAGS       (OPTST_DISABLED)

/*
 *  No_Fmemopen option description:
 */
static char const zNo_FmemopenText[] =
        "Do not use in-mem streams";
static char const zNo_Fmemopen_NAME[]        = "NO_FMEMOPEN";
static char const zNo_Fmemopen_Name[]        = "no-fmemopen";
#define NO_FMEMOPEN_FLAGS       (OPTST_DISABLED)

/*
 *  Equate option description:
 */
static char const zEquateText[] =
        "characters considered equivalent";
static char const zEquate_NAME[]             = "EQUATE";
static char const zEquate_Name[]             = "equate";
static char const zEquateDefaultArg[]          = "_-^";
#define EQUATE_FLAGS       (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  Writable option description:
 */
static char const zWritableText[] =
        "Allow output files to be writable";
static char const zWritable_NAME[]           = "WRITABLE";
static char const zNotWritable_Name[]        = "not-writable";
static char const zNotWritable_Pfx[]         = "not";
#define zWritable_Name               (zNotWritable_Name + 4)
#define WRITABLE_FLAGS       (OPTST_DISABLED | OPTST_NO_INIT)

/*
 *  Doc_Debug option description:
 */
static char const zDoc_DebugText[] =
        "The following options are often useful while debugging new templates:";
#define DOC_DEBUG_FLAGS       (OPTST_DOCUMENT | OPTST_NO_INIT)

/*
 *  Loop_Limit option description:
 */
static char const zLoop_LimitText[] =
        "Limit on increment loops";
static char const zLoop_Limit_NAME[]         = "LOOP_LIMIT";
static char const zLoop_Limit_Name[]         = "loop-limit";
#define zLoop_LimitDefaultArg        ((char const*)256)
#define LOOP_LIMIT_FLAGS       (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC) \
        | OPTST_SCALED_NUM)

/*
 *  Shell option description:
 */
#ifdef SHELL_ENABLED
static char const zShellText[] =
        "name or path name of shell to use";
static char const zShell_NAME[]              = "SHELL";
static char const zShell_Name[]              = "shell";
#define SHELL_FLAGS       (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

#else   /* disable Shell */
#define SHELL_FLAGS       (OPTST_OMITTED | OPTST_NO_INIT)
#define zShell_NAME      NULL
#define zShellText       NULL
#define zShell_Name      NULL
#endif  /* SHELL_ENABLED */

/*
 *  Timeout option description:
 */
#ifdef SHELL_ENABLED
static char const zTimeoutText[] =
        "Time limit for server shell";
static char const zTimeout_NAME[]            = "TIMEOUT";
static char const zTimeout_Name[]            = "timeout";
#define TIMEOUT_FLAGS       (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_NUMERIC))

#else   /* disable Timeout */
#define TIMEOUT_FLAGS       (OPTST_OMITTED | OPTST_NO_INIT)
#define zTimeout_NAME      NULL
#define zTimeoutText       NULL
#define zTimeout_Name      NULL
#endif  /* SHELL_ENABLED */

/*
 *  Trace option description:
 */
static char const zTraceText[] =
        "tracing level of detail";
static char const zTrace_NAME[]              = "TRACE";
static char const zTrace_Name[]              = "trace";
#define zTraceDefaultArg             ((char const*)TRACE_NOTHING)
#define TRACE_FLAGS       (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_ENUMERATION))

/*
 *  Trace_Out option description:
 */
static char const zTrace_OutText[] =
        "tracing output file or filter";
static char const zTrace_Out_NAME[]          = "TRACE_OUT";
static char const zTrace_Out_Name[]          = "trace-out";
#define TRACE_OUT_FLAGS       (OPTST_DISABLED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  Show_Defs option description:
 */
#ifdef DEBUG_ENABLED
static char const zShow_DefsText[] =
        "Show the definition tree";
static char const zShow_Defs_NAME[]          = "SHOW_DEFS";
static char const zShow_Defs_Name[]          = "show-defs";
#define SHOW_DEFS_FLAGS       (OPTST_DISABLED | OPTST_NO_INIT)

#else   /* disable Show_Defs */
#define SHOW_DEFS_FLAGS       (OPTST_OMITTED | OPTST_NO_INIT)
#define zShow_Defs_NAME      NULL
static char const zShow_Defs_Name[] = "show-defs";
#define zShow_DefsText       NULL
#endif  /* DEBUG_ENABLED */

/*
 *  Used_Defines option description:
 */
static char const zUsed_DefinesText[] =
        "Show the definitions used";
static char const zUsed_Defines_NAME[]       = "USED_DEFINES";
static char const zUsed_Defines_Name[]       = "used-defines";
#define USED_DEFINES_FLAGS       (OPTST_DISABLED | OPTST_NO_INIT)

/*
 *  Doc_Control option description:
 */
static char const zDoc_ControlText[] =
        "These options can be used to control what gets processed\n\
in the definitions files and template files.";
#define DOC_CONTROL_FLAGS       (OPTST_DOCUMENT | OPTST_NO_INIT)

/*
 *  Define option description:
 */
static char const zDefineText[] =
        "name to add to definition list";
static char const zDefine_NAME[]             = "DEFINE";
static char const zDefine_Name[]             = "define";
#define DEFINE_FLAGS       (OPTST_DISABLED | OPTST_STACKED \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  Undefine option description:
 */
static char const zUndefineText[] =
        "definition list removal pattern";
static char const zUndefine_NAME[]           = "UNDEFINE";
static char const zUndefine_Name[]           = "undefine";
#define UNDEFINE_FLAGS       (OPTST_DISABLED | OPTST_NO_INIT \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING))

/*
 *  Doc_Dependencies option description:
 */
static char const zDoc_DependenciesText[] =
        "These options can be used to automate dependency tracking.";
#define DOC_DEPENDENCIES_FLAGS       (OPTST_DOCUMENT | OPTST_NO_INIT)

/*
 *  Make_Dep option description:
 */
static char const zMake_DepText[] =
        "emit make dependency file";
static char const zMake_Dep_NAME[]           = "MAKE_DEP";
static char const zMake_Dep_Name[]           = "make-dep";
#define MAKE_DEP_FLAGS       (OPTST_DISABLED | OPTST_NO_INIT \
        | OPTST_SET_ARGTYPE(OPARG_TYPE_STRING) | OPTST_ARG_OPTIONAL)

/*
 *  Core option description:
 */
#ifdef HAVE_SYS_RESOURCE_H
static char const zCoreText[] =
        "Leave a core dump on a failure exit";
static char const zCore_NAME[]               = "CORE";
static char const zCore_Name[]               = "core";
#define CORE_FLAGS       (OPTST_DISABLED)

#else   /* disable Core */
#define CORE_FLAGS       (OPTST_OMITTED | OPTST_NO_INIT)
#define zCore_NAME      NULL
#define zCoreText       NULL
#define zCore_Name      NULL
#endif  /* HAVE_SYS_RESOURCE_H */

/*
 *  Help/More_Help/Version option descriptions:
 */
static char const zHelpText[]          = "Display extended usage information and exit";
static char const zHelp_Name[]         = "help";
#ifdef HAVE_WORKING_FORK
#define OPTST_MORE_HELP_FLAGS   (OPTST_IMM | OPTST_NO_INIT)
static char const zMore_Help_Name[]    = "more-help";
static char const zMore_HelpText[]     = "Extended usage information passed thru pager";
#else
#define OPTST_MORE_HELP_FLAGS   (OPTST_OMITTED | OPTST_NO_INIT)
#define zMore_Help_Name   NULL
#define zMore_HelpText    NULL
#endif
#ifdef NO_OPTIONAL_OPT_ARGS
#  define OPTST_VERSION_FLAGS   OPTST_IMM | OPTST_NO_INIT
#else
#  define OPTST_VERSION_FLAGS   OPTST_SET_ARGTYPE(OPARG_TYPE_STRING) | \
                                OPTST_ARG_OPTIONAL | OPTST_IMM | OPTST_NO_INIT
#endif

static char const zVersionText[]       = "Output version information and exit";
static char const zVersion_Name[]      = "version";
static char const zUsageText[]         = "Abbreviated usage to stdout";
static char const zUsage_Name[]        = "usage";
static char const zSave_OptsText[]     = "Save the option state to a config file";
static char const zSave_Opts_Name[]    = "save-opts";
static char const zLoad_OptsText[]     = "Load options from a config file";
static char const zLoad_Opts_NAME[]    = "LOAD_OPTS";
static char const zNotLoad_Opts_Name[] = "no-load-opts";
static char const zNotLoad_Opts_Pfx[]  = "no";
#define zLoad_Opts_Name   (zNotLoad_Opts_Name + 3)
/*
 *  Declare option callback procedures
 */
#ifdef HAVE_DLOPEN
  static tOptProc doOptLoad_Functions;
#else /* not HAVE_DLOPEN */
# define doOptLoad_Functions NULL
#endif /* def/not HAVE_DLOPEN */
#ifdef SHELL_ENABLED
  static tOptProc doOptShell;
#else /* not SHELL_ENABLED */
# define doOptShell NULL
#endif /* def/not SHELL_ENABLED */
#ifdef SHELL_ENABLED
  static tOptProc doOptTimeout;
#else /* not SHELL_ENABLED */
# define doOptTimeout NULL
#endif /* def/not SHELL_ENABLED */
extern tOptProc
    config_dep,          optionBooleanVal,    optionNestedVal,
    optionNumericVal,    optionPagedUsage,    optionPrintVersion,
    optionResetOpt,      optionStackArg,      optionTimeDate,
    optionTimeVal,       optionUnstackArg,    optionVersionStderr;
static tOptProc
    doOptLib_Template,  doOptLoad_Scheme,   doOptLoop_Limit,
    doOptOverride_Tpl,  doOptSelect_Suffix, doOptTrace,
    doUsageOpt;

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *  Define the Autogen Option Descriptions.
 */
static tOptDesc optDesc[OPTION_CT] = {
  {  /* entry idx, value */ 0, VALUE_OPT_TEMPL_DIRS,
     /* equiv idx, value */ 0, VALUE_OPT_TEMPL_DIRS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ TEMPL_DIRS_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionStackArg,
     /* desc, NAME, name */ zTempl_DirsText, zTempl_Dirs_NAME, zTempl_Dirs_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 1, VALUE_OPT_OVERRIDE_TPL,
     /* equiv idx, value */ 1, VALUE_OPT_OVERRIDE_TPL,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OVERRIDE_TPL_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptOverride_Tpl,
     /* desc, NAME, name */ zOverride_TplText, zOverride_Tpl_NAME, zOverride_Tpl_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 2, VALUE_OPT_LIB_TEMPLATE,
     /* equiv idx, value */ 2, VALUE_OPT_LIB_TEMPLATE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ LIB_TEMPLATE_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptLib_Template,
     /* desc, NAME, name */ zLib_TemplateText, zLib_Template_NAME, zLib_Template_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 3, VALUE_OPT_BASE_NAME,
     /* equiv idx, value */ 3, VALUE_OPT_BASE_NAME,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ BASE_NAME_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zBase_NameText, zBase_Name_NAME, zBase_Name_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 4, VALUE_OPT_DEFINITIONS,
     /* equiv idx, value */ 4, VALUE_OPT_DEFINITIONS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ DEFINITIONS_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zDefinitionsText, zDefinitions_NAME, zDefinitions_Name,
     /* disablement strs */ zNotDefinitions_Name, zNotDefinitions_Pfx },

  {  /* entry idx, value */ 5, VALUE_OPT_LOAD_SCHEME,
     /* equiv idx, value */ 5, VALUE_OPT_LOAD_SCHEME,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ LOAD_SCHEME_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptLoad_Scheme,
     /* desc, NAME, name */ zLoad_SchemeText, zLoad_Scheme_NAME, zLoad_Scheme_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 6, VALUE_OPT_LOAD_FUNCTIONS,
     /* equiv idx, value */ 6, VALUE_OPT_LOAD_FUNCTIONS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ LOAD_FUNCTIONS_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptLoad_Functions,
     /* desc, NAME, name */ zLoad_FunctionsText, zLoad_Functions_NAME, zLoad_Functions_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 7, VALUE_OPT_SKIP_SUFFIX,
     /* equiv idx, value */ 7, VALUE_OPT_SKIP_SUFFIX,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ SKIP_SUFFIX_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, aSkip_SuffixCantList,
     /* option proc      */ optionStackArg,
     /* desc, NAME, name */ zSkip_SuffixText, zSkip_Suffix_NAME, zSkip_Suffix_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 8, VALUE_OPT_SELECT_SUFFIX,
     /* equiv idx, value */ 8, VALUE_OPT_SELECT_SUFFIX,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ SELECT_SUFFIX_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptSelect_Suffix,
     /* desc, NAME, name */ zSelect_SuffixText, zSelect_Suffix_NAME, zSelect_Suffix_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 9, VALUE_OPT_SOURCE_TIME,
     /* equiv idx, value */ 9, VALUE_OPT_SOURCE_TIME,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SOURCE_TIME_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zSource_TimeText, zSource_Time_NAME, zSource_Time_Name,
     /* disablement strs */ zNotSource_Time_Name, zNotSource_Time_Pfx },

  {  /* entry idx, value */ 10, VALUE_OPT_NO_FMEMOPEN,
     /* equiv idx, value */ 10, VALUE_OPT_NO_FMEMOPEN,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ NO_FMEMOPEN_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zNo_FmemopenText, zNo_Fmemopen_NAME, zNo_Fmemopen_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 11, VALUE_OPT_EQUATE,
     /* equiv idx, value */ 11, VALUE_OPT_EQUATE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ EQUATE_FLAGS, 0,
     /* last opt argumnt */ { zEquateDefaultArg },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zEquateText, zEquate_NAME, zEquate_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 12, VALUE_OPT_WRITABLE,
     /* equiv idx, value */ 12, VALUE_OPT_WRITABLE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ WRITABLE_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zWritableText, zWritable_NAME, zWritable_Name,
     /* disablement strs */ zNotWritable_Name, zNotWritable_Pfx },

  {  /* entry idx, value */ 0, 0,
     /* equiv idx, value */ 0, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 0, 0,
     /* opt state flags  */ DOC_DEBUG_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zDoc_DebugText, NULL, NULL,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 14, VALUE_OPT_LOOP_LIMIT,
     /* equiv idx, value */ 14, VALUE_OPT_LOOP_LIMIT,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ LOOP_LIMIT_FLAGS, 0,
     /* last opt argumnt */ { zLoop_LimitDefaultArg },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptLoop_Limit,
     /* desc, NAME, name */ zLoop_LimitText, zLoop_Limit_NAME, zLoop_Limit_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 15, VALUE_OPT_SHELL,
     /* equiv idx, value */ 15, VALUE_OPT_SHELL,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SHELL_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptShell,
     /* desc, NAME, name */ zShellText, zShell_NAME, zShell_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 16, VALUE_OPT_TIMEOUT,
     /* equiv idx, value */ 16, VALUE_OPT_TIMEOUT,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ TIMEOUT_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptTimeout,
     /* desc, NAME, name */ zTimeoutText, zTimeout_NAME, zTimeout_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 17, VALUE_OPT_TRACE,
     /* equiv idx, value */ 17, VALUE_OPT_TRACE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ TRACE_FLAGS, 0,
     /* last opt argumnt */ { zTraceDefaultArg },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doOptTrace,
     /* desc, NAME, name */ zTraceText, zTrace_NAME, zTrace_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 18, VALUE_OPT_TRACE_OUT,
     /* equiv idx, value */ 18, VALUE_OPT_TRACE_OUT,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ TRACE_OUT_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zTrace_OutText, zTrace_Out_NAME, zTrace_Out_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 19, VALUE_OPT_SHOW_DEFS,
     /* equiv idx, value */ 19, VALUE_OPT_SHOW_DEFS,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ SHOW_DEFS_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zShow_DefsText, zShow_Defs_NAME, zShow_Defs_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 20, VALUE_OPT_USED_DEFINES,
     /* equiv idx, value */ 20, VALUE_OPT_USED_DEFINES,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ USED_DEFINES_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zUsed_DefinesText, zUsed_Defines_NAME, zUsed_Defines_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 0, 0,
     /* equiv idx, value */ 0, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 0, 0,
     /* opt state flags  */ DOC_CONTROL_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zDoc_ControlText, NULL, NULL,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 22, VALUE_OPT_DEFINE,
     /* equiv idx, value */ 22, VALUE_OPT_DEFINE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ DEFINE_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionStackArg,
     /* desc, NAME, name */ zDefineText, zDefine_NAME, zDefine_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 23, VALUE_OPT_UNDEFINE,
     /* equiv idx, value */ NOLIMIT, NOLIMIT,
     /* equivalenced to  */ INDEX_OPT_DEFINE,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ UNDEFINE_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionUnstackArg,
     /* desc, NAME, name */ zUndefineText, zUndefine_NAME, zUndefine_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 0, 0,
     /* equiv idx, value */ 0, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 0, 0,
     /* opt state flags  */ DOC_DEPENDENCIES_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zDoc_DependenciesText, NULL, NULL,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 25, VALUE_OPT_MAKE_DEP,
     /* equiv idx, value */ 25, VALUE_OPT_MAKE_DEP,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ MAKE_DEP_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ config_dep,
     /* desc, NAME, name */ zMake_DepText, zMake_Dep_NAME, zMake_Dep_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ 26, VALUE_OPT_CORE,
     /* equiv idx, value */ 26, VALUE_OPT_CORE,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ CORE_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zCoreText, zCore_NAME, zCore_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_VERSION, VALUE_OPT_VERSION,
     /* equiv idx value  */ NO_EQUIVALENT, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OPTST_VERSION_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionPrintVersion,
     /* desc, NAME, name */ zVersionText, NULL, zVersion_Name,
     /* disablement strs */ NULL, NULL },



  {  /* entry idx, value */ INDEX_OPT_HELP, VALUE_OPT_HELP,
     /* equiv idx value  */ NO_EQUIVALENT, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OPTST_IMM | OPTST_NO_INIT, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ doUsageOpt,
     /* desc, NAME, name */ zHelpText, NULL, zHelp_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_MORE_HELP, VALUE_OPT_MORE_HELP,
     /* equiv idx value  */ NO_EQUIVALENT, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OPTST_MORE_HELP_FLAGS, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL,  NULL,
     /* option proc      */ optionPagedUsage,
     /* desc, NAME, name */ zMore_HelpText, NULL, zMore_Help_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_USAGE, VALUE_OPT_USAGE,
     /* equiv idx value  */ NO_EQUIVALENT, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OPTST_IMM | OPTST_NO_INIT, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL,  NULL,
     /* option proc      */ doUsageOpt,
     /* desc, NAME, name */ zUsageText, NULL, zUsage_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_SAVE_OPTS, VALUE_OPT_SAVE_OPTS,
     /* equiv idx value  */ NO_EQUIVALENT, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, 1, 0,
     /* opt state flags  */ OPTST_SET_ARGTYPE(OPARG_TYPE_STRING)
                          | OPTST_ARG_OPTIONAL | OPTST_NO_INIT, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL,  NULL,
     /* option proc      */ NULL,
     /* desc, NAME, name */ zSave_OptsText, NULL, zSave_Opts_Name,
     /* disablement strs */ NULL, NULL },

  {  /* entry idx, value */ INDEX_OPT_LOAD_OPTS, VALUE_OPT_LOAD_OPTS,
     /* equiv idx value  */ NO_EQUIVALENT, 0,
     /* equivalenced to  */ NO_EQUIVALENT,
     /* min, max, act ct */ 0, NOLIMIT, 0,
     /* opt state flags  */ OPTST_SET_ARGTYPE(OPARG_TYPE_STRING)
			  | OPTST_DISABLE_IMM, 0,
     /* last opt argumnt */ { NULL },
     /* arg list/cookie  */ NULL,
     /* must/cannot opts */ NULL, NULL,
     /* option proc      */ optionLoadOpt,
     /* desc, NAME, name */ zLoad_OptsText, zLoad_Opts_NAME, zLoad_Opts_Name,
     /* disablement strs */ zNotLoad_Opts_Name, zNotLoad_Opts_Pfx }
};

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *  Define the Autogen Option Environment
 */
static char const zPROGNAME[8] = "AUTOGEN";
static char const zUsageTitle[141] =
"autogen (GNU AutoGen) - The Automated Program Generator - Ver. 5.12\n\
USAGE:  %s [ -<flag> [<val>] | --<name>[{=| }<val>] ]... [ <def-file> ]\n";
static char const zRcName[11] = ".autogenrc";
static char const * const apzHomeList[3] = {
    "$HOME",
    ".",
    NULL };

static char const zBugsAddr[36]    = "autogen-users@lists.sourceforge.net";
static char const zExplain[] = "\n\
AutoGen creates text files from templates using external definitions.\n";
static char const zDetail[123] = "\n\
AutoGen is a tool designed for generating program files that contain\n\
repetitive text with varied substitutions.\n";
static char const zFullVersion[] = AUTOGEN_FULL_VERSION;
/* extracted from optcode.tlib near line 515 */

#if defined(ENABLE_NLS)
# define OPTPROC_BASE OPTPROC_TRANSLATE
  static tOptionXlateProc translate_option_strings;
#else
# define OPTPROC_BASE OPTPROC_NONE
# define translate_option_strings NULL
#endif /* ENABLE_NLS */


#define autogen_full_usage NULL
#define autogen_short_usage NULL
#ifndef  PKGDATADIR
# define PKGDATADIR ""
#endif

#ifndef  WITH_PACKAGER
# define autogen_packager_info NULL
#else
static char const autogen_packager_info[] =
    "Packaged by " WITH_PACKAGER

# ifdef WITH_PACKAGER_VERSION
        " ("WITH_PACKAGER_VERSION")"
# endif

# ifdef WITH_PACKAGER_BUG_REPORTS
    "\nReport autogen bugs to " WITH_PACKAGER_BUG_REPORTS
# endif
    "\n";
#endif

tOptions autogenOptions = {
    OPTIONS_STRUCT_VERSION,
    0, NULL,                    /* original argc + argv    */
    ( OPTPROC_BASE
    + OPTPROC_ERRSTOP
    + OPTPROC_SHORTOPT
    + OPTPROC_LONGOPT
    + OPTPROC_NO_REQ_OPT
    + OPTPROC_NEGATIONS
    + OPTPROC_ENVIRON ),
    0, NULL,                    /* current option index, current option */
    NULL,         NULL,         zPROGNAME,
    zRcName,      zCopyright,   zLicenseDescrip,
    zFullVersion, apzHomeList,  zUsageTitle,
    zExplain,     zDetail,      optDesc,
    zBugsAddr,                  /* address to send bugs to */
    NULL, NULL,                 /* extensions/saved state  */
    optionUsage, /* usage procedure */
    translate_option_strings,   /* translation procedure */
    /*
     *  Indexes to special options
     */
    { INDEX_OPT_MORE_HELP, /* more-help option index */
      INDEX_OPT_SAVE_OPTS, /* save option index */
      NO_EQUIVALENT, /* '-#' option index */
      NO_EQUIVALENT /* index of default opt */
    },
    33 /* full option count */, 27 /* user option count */,
    autogen_full_usage, autogen_short_usage,
    NULL, NULL,
    PKGDATADIR, autogen_packager_info
};

/*
 *  Create the static procedure(s) declared above.
 */
static void
doUsageOpt(tOptions * pOptions, tOptDesc * pOptDesc)
{
    int ex_code = (pOptDesc->optIndex == INDEX_OPT_HELP)
        ? AUTOGEN_EXIT_SUCCESS : EX_USAGE;
    (void)pOptions;
    USAGE(ex_code);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *   For the override-tpl option.
 */
static void
doOptOverride_Tpl(tOptions* pOptions, tOptDesc* pOptDesc)
{
    /* extracted from opts.def, line 153 */
    pzTemplFileName = pOptDesc->optArg.argString;
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *   For the lib-template option.
 */
static void
doOptLib_Template(tOptions* pOptions, tOptDesc* pOptDesc)
{
    /* extracted from opts.def, line 174 */
    tTemplate* pT;
    procState = PROC_STATE_LIB_LOAD;
    pT = loadTemplate(pOptDesc->optArg.argString, NULL);
    unloadTemplate(pT);
    procState = PROC_STATE_OPTIONS;
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *   For the load-scheme option.
 */
static void
doOptLoad_Scheme(tOptions* pOptions, tOptDesc* pOptDesc)
{
    /* extracted from opts.def, line 254 */
    teProcState saveState = procState;
    char* pz;
    char  zPath[MAXPATHLEN];
    static char const * const apzSfx[] = { "scm", NULL };

    if (! SUCCESSFUL(
        findFile(pOptDesc->optArg.argString, zPath, apzSfx, NULL))) {

        usage_message("Cannot locate scheme file `%s'\n",
                      pOptDesc->optArg.argString);
        /* NOTREACHED */
    }

    pz = aprf("(load \"%s\")", zPath);
    procState = PROC_STATE_GUILE_PRELOAD;
    (void)ag_scm_c_eval_string_from_file_line(
                   pz, __FILE__, __LINE__);
    free(pz);
    procState = saveState;
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *   For the load-functions option, when HAVE_DLOPEN is #define-d.
 */
#ifdef HAVE_DLOPEN
static void
doOptLoad_Functions(tOptions* pOptions, tOptDesc* pOptDesc)
{
    /* extracted from opts.def, line 294 */
    void* hdl = dlopen(
        pOptDesc->optArg.argString, RTLD_NOW|RTLD_GLOBAL);
    init_proc_t* proc;

    if (hdl == NULL) {
        char const* pzErr = dlerror();
        fprintf(stderr, "dlopen(%s) error %d\n%s\n",
                pOptDesc->optArg.argString, errno, pzErr);
        exit(EXIT_FAILURE);
    }
    proc = (init_proc_t*)dlsym(hdl, "scm_init");
    if (proc == NULL) {
        fprintf(stderr, "dlsym(scm_init) not found in %s\n"
                "\tyou must initialize the library yourself\n",
                pOptDesc->optArg.argString);
    }
    else (*proc)();
}
#endif /* defined HAVE_DLOPEN */

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *   For the select-suffix option.
 */
static void
doOptSelect_Suffix(tOptions* pOptions, tOptDesc* pOptDesc)
{
    /* extracted from opts.def, line 357 */
    char const * arg = pOptDesc->optArg.argString;
    if ((arg != NULL) && (*arg != NUL))
        (void)do_suffix(arg, NULL, -1);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *   For the loop-limit option.
 */
static void
doOptLoop_Limit(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static const struct {long const rmin, rmax;} rng[2] = {
        { -1, LONG_MIN },  { 1, 0x1000000 } };
    int  ix;

    if (pOptions <= OPTPROC_EMIT_LIMIT)
        goto emit_ranges;
    optionNumericVal(pOptions, pOptDesc);

    for (ix = 0; ix < 2; ix++) {
        if (pOptDesc->optArg.argInt < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (pOptDesc->optArg.argInt == rng[ix].rmin)
            return;
        if (rng[ix].rmax == LONG_MIN)
            continue;
        if (pOptDesc->optArg.argInt <= rng[ix].rmax)
            return;
    }

    option_usage_fp = stderr;

emit_ranges:

    optionShowRange(pOptions, pOptDesc, (void *)rng, 2);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *   For the shell option, when SHELL_ENABLED is #define-d.
 */
#ifdef SHELL_ENABLED
static void
doOptShell(tOptions* pOptions, tOptDesc* pOptDesc)
{
    /* extracted from opts.def, line 489 */
    pzShellProgram = pOptDesc->optArg.argString;
}
#endif /* defined SHELL_ENABLED */

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *   For the timeout option, when SHELL_ENABLED is #define-d.
 */
#ifdef SHELL_ENABLED
static void
doOptTimeout(tOptions* pOptions, tOptDesc* pOptDesc)
{
    static const struct {long const rmin, rmax;} rng[1] = {
        { 0, 3600 } };
    int  ix;

    if (pOptions <= OPTPROC_EMIT_LIMIT)
        goto emit_ranges;
    optionNumericVal(pOptions, pOptDesc);

    for (ix = 0; ix < 1; ix++) {
        if (pOptDesc->optArg.argInt < rng[ix].rmin)
            continue;  /* ranges need not be ordered. */
        if (pOptDesc->optArg.argInt == rng[ix].rmin)
            return;
        if (rng[ix].rmax == LONG_MIN)
            continue;
        if (pOptDesc->optArg.argInt <= rng[ix].rmax)
            return;
    }

    option_usage_fp = stderr;

emit_ranges:

    optionShowRange(pOptions, pOptDesc, (void *)rng, 1);
}
#endif /* defined SHELL_ENABLED */

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 *   For the trace option.
 */
static void
doOptTrace(tOptions* pOptions, tOptDesc* pOptDesc)
{

/* extracted from optmain.tlib near line 880 */
    static char const * const azNames[7] = {
        "nothing",        "debug-message",  "server-shell",   "templates",
        "block-macros",   "expressions",    "everything"
    };

    if (pOptions <= OPTPROC_EMIT_LIMIT) {
        (void) optionEnumerationVal(pOptions, pOptDesc, azNames, 7);
        return; /* protect AutoOpts client code from internal callbacks */
    }

    pOptDesc->optArg.argEnum =
        optionEnumerationVal(pOptions, pOptDesc, azNames, 7);

}
/* extracted from optcode.tlib near line 666 */

void
vusage_message(char const * fmt, va_list ap)
{
    char const * er_fmt = _("%s usage error:\n");
    fprintf(stderr, er_fmt, autogenOptions.pzProgName);
    vfprintf(stderr, fmt, ap);
    USAGE(AUTOGEN_EXIT_OPTION_ERROR);
    /* NOTREACHED */
}

void
usage_message(char const * fmt, ...)
{
    va_list ap;
    va_start(ap, fmt);
    vusage_message(fmt, ap);
    /* NOTREACHED */
    va_end(ap);
}

#if ENABLE_NLS
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <autoopts/usage-txt.h>

static char* AO_gettext(char const* pz);
static void  coerce_it(void** s);

static char*
AO_gettext(char const* pz)
{
    char* pzRes;
    if (pz == NULL)
        return NULL;
    pzRes = _(pz);
    if (pzRes == pz)
        return pzRes;
    pzRes = strdup(pzRes);
    if (pzRes == NULL) {
        fputs(_("No memory for duping translated strings\n"), stderr);
        exit(AUTOGEN_EXIT_OPTION_ERROR);
    }
    return pzRes;
}

static void coerce_it(void** s) { *s = AO_gettext(*s);
}

/*
 *  This invokes the translation code (e.g. gettext(3)).
 */
static void
translate_option_strings(void)
{
    tOptions * const pOpt = &autogenOptions;

    /*
     *  Guard against re-translation.  It won't work.  The strings will have
     *  been changed by the first pass through this code.  One shot only.
     */
    if (option_usage_text.field_ct != 0) {
        /*
         *  Do the translations.  The first pointer follows the field count
         *  field.  The field count field is the size of a pointer.
         */
        tOptDesc * pOD = pOpt->pOptDesc;
        char **    ppz = (char**)(void*)&(option_usage_text);
        int        ix  = option_usage_text.field_ct;

        do {
            ppz++;
            *ppz = AO_gettext(*ppz);
        } while (--ix > 0);

        coerce_it((void*)&(pOpt->pzCopyright));
        coerce_it((void*)&(pOpt->pzCopyNotice));
        coerce_it((void*)&(pOpt->pzFullVersion));
        coerce_it((void*)&(pOpt->pzUsageTitle));
        coerce_it((void*)&(pOpt->pzExplain));
        coerce_it((void*)&(pOpt->pzDetail));
        coerce_it((void*)&(pOpt->pzPackager));
        option_usage_text.field_ct = 0;

        for (ix = pOpt->optCt; ix > 0; ix--, pOD++)
            coerce_it((void*)&(pOD->pzText));
    }

    if ((pOpt->fOptSet & OPTPROC_NXLAT_OPT_CFG) == 0) {
        tOptDesc * pOD = pOpt->pOptDesc;
        int        ix;

        for (ix = pOpt->optCt; ix > 0; ix--, pOD++) {
            coerce_it((void*)&(pOD->pz_Name));
            coerce_it((void*)&(pOD->pz_DisableName));
            coerce_it((void*)&(pOD->pz_DisablePfx));
        }
        /* prevent re-translation */
        autogenOptions.fOptSet |= OPTPROC_NXLAT_OPT_CFG | OPTPROC_NXLAT_OPT;
    }
}

#endif /* ENABLE_NLS */

#ifdef  __cplusplus
}
#endif
/* opts.c ends here */
